<?php

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

$previewUrl = $block->escapeUrl($block->getUrl('*/*/preview'));
$sendUrl = $block->escapeUrl($block->getUrl('*/*/send'));
?>
<script>
    LokiComponentExtender.add('ExampleMixin', () => {
        return {
            preview() {
                const params = this.getEmailTesterParameters();
                if (!params) {
                    return;
                }

                const url = '<?= $previewUrl ?>' + this.getEmailTesterParameters();
                Alpine.store('Message').addMessage('error', 'Previewing ' + url);
            },
            send() {
                const params = this.getEmailTesterParameters();
                if (!params) {
                    return;
                }

                const url = '<?= $sendUrl ?>' + this.getEmailTesterParameters();
                Alpine.store('Message').addMessage('error', 'Send ' + url);
            },
            addError(message) {
                Alpine.store('Message').addMessage('error', message);
            },
            getEmailTesterParameters() {
                if (!this.sender) {
                    this.addError('Please add a sender');
                    return false;
                }

                return '?' +
                    'sender=' + this.sender +
                    'email=' + this.email +
                    'store_id=' + this.store_id +
                    'template=' + this.template +
                    'customer_id=' + this.customer_id +
                    'product_id=' + this.product_id +
                    'order_id=' + this.order_id;
            }
        };
    });
</script>
