<?php

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

$previewUrl = $block->escapeUrl($block->getUrl('*/*/preview'));
$sendUrl = $block->escapeUrl($block->getUrl('*/*/send'));
?>
<script>
    LokiComponentExtender.add('ExampleMixin', () => {
        return {
            preview() {
                const params = this.getEmailTesterParameters();
                if (!params) {
                    return;
                }

                const url = '<?= $previewUrl ?>?' + new URLSearchParams(params).toString();
                window.open(url);
            },
            send() {
                const params = this.getEmailTesterParameters();
                if (!params) {
                    return;
                }

                const url = '<?= $sendUrl ?>?' + new URLSearchParams(params).toString();
                window.open(url);
            },
            addError(message) {
                Alpine.store('Message').addMessage('error', message);
            },
            getEmailTesterParameters() {
                const fields = {
                    'mail_from': 'Sender',
                    'mail_to': 'Recipient',
                    'store_id': 'Store ID',
                    'template': 'Email Template',
                    'customer_id': 'Customer',
                    'product_id': 'Product',
                    'order_id': 'Order',
                };

                let valid = true;
                const values = {};

                for (const [key, label] of Object.entries(fields)) {
                    if (!this.item[key]) {
                        this.addError('Please add a valid ' + label);
                        valid = false;
                        return false;
                    }

                    values[key] = this.item[key];
                }

                if (!valid) {
                    return false;
                }

                return values;
            }
        };
    });
</script>
