<?php
/**
 * EmailTester2 extension for Magento
 *
 * @package     Yireo_EmailTester2
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2015 Yireo.com
 * @license     Open Software License
 */

/** @var $block Yireo\EmailTester2\Block\Adminhtml\Script */
?>
<script type="text/x-magento-init">
{
    "*": {
        "emailtester" : {
            "customer_ajax_url": "<?= $block->getUrl('*/ajax/customer') ?>",
            "product_ajax_url": "<?= $block->getUrl('*/ajax/product') ?>",
            "order_ajax_url": "<?= $block->getUrl('*/ajax/order') ?>"
        }
    }
}
</script>

<script>
    function submitEmailTesterFormToUrl(formId, url) {
        var form = jQuery('#' + formId);
        form.attr('action', url);
        form.submit();
    }
</script>