<?php
/**
 * EmailTester2 extension for Magento
 *
 * @package     Yireo_EmailTester2
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2015 Yireo.com
 * @license     Open Software License
 */

/** @var $block Yireo\EmailTester2\Block\Adminhtml\Script */
?>
<script>
    var emailtester_customer_ajax_url = '<?php echo $block->getUrl('*/ajax/customer'); ?>?form_key=' + window.FORM_KEY;
    var emailtester_product_ajax_url = '<?php echo $block->getUrl('*/ajax/product'); ?>?form_key=' + window.FORM_KEY;
    var emailtester_order_ajax_url = '<?php echo $block->getUrl('*/ajax/order'); ?>?form_key=' + window.FORM_KEY;
    require(['jquery','Yireo_EmailTester2/js/emailtester'],function($){});
</script>
<a href="<?php echo $block->getUrl('*/ajax/customer'); ?>">test</a>