<?php
/**
 * EmailTester2 extension for Magento
 *
 * @package     Yireo_EmailTester2
 * @author      Yireo (https://www.yireo.com/)
 * @copyright   Copyright (c) 2018 Yireo.com
 * @license     Open Software License
 */

/** @var $block Magento\Backend\Block\Template */
?>
<script type="text/x-magento-init">
{
    "*": {
        "emailtester" : {
            "customer_ajax_url": "<?= $block->escapeUrl($block->getUrl('*/ajax/customer')) ?>",
            "product_ajax_url": "<?= $block->escapeUrl($block->getUrl('*/ajax/product')) ?>",
            "order_ajax_url": "<?= $block->escapeUrl($block->getUrl('*/ajax/order')) ?>"
        }
    }
}
</script>

<?php /*
<script>
    var window.submitEmailTesterFormToUrl;
    require(['jquery'], function($) {
         window.submitEmailTesterFormToUrl = function(formId, url) {
            var form = $('#' + formId);
            form.attr('action', url);
            form.submit();
        }
    });
</script>
*/ ?>